language: node_js
node_js:
  - '4'
  - '0.12'
services:
  - rabbitmq
before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get install --force-yes --yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
