language: node_js
node_js:
  - "4.0"
  - "0.12"
services:
  - rabbitmq
before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get install --force-yes --yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev
matrix:
  allow_failures:
    - node_js: "4.0"
